package cplib

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mjwhitta/errors"
)

// GenerateGo will generate Go source for all of the exports and
// imports provided and write to the provided filename.
func GenerateGo(
	bin string,
	fn string,
	tags string,
	exports []string,
	imports []Import,
	appendToFile bool,
) (e error) {
	var f *os.File
	var newline bool
	var sb strings.Builder
	var tool string = "github.com/mjwhitta/cplib"

	if !appendToFile {
		// Write the header
		sb.WriteString(fmt.Sprintf("//go:build %s\n\n", tags))
		sb.WriteString(
			fmt.Sprintf(
				"// Code generated by %s; DO NOT EDIT.\n",
				tool,
			),
		)
		sb.WriteString("package main\n\n")
		sb.WriteString("import \"C\"\n\n")
	}

	// Write each export
	for _, ex := range exports {
		if newline || appendToFile {
			sb.WriteString("\n")
		}

		sb.WriteString(
			fmt.Sprintf("// %s from %s.\n", ex, filepath.Base(bin)),
		)
		sb.WriteString(
			fmt.Sprintf("//\n//export %s\nfunc %s() {}\n", ex, ex),
		)

		newline = true
	}

	// Write each import
	for _, im := range imports {
		switch {
		case newline || (len(exports) > 0):
			sb.WriteString("\n")
		case appendToFile && (len(exports) == 0):
			sb.WriteString("\n")
		}

		sb.WriteString(
			fmt.Sprintf(
				"// %s from %s called by %s.\n",
				im.Name,
				im.Library,
				filepath.Base(bin),
			),
		)
		sb.WriteString(
			fmt.Sprintf(
				"//\n//export %s\nfunc %s() {}\n",
				im.Name,
				im.Name,
			),
		)

		newline = true
	}

	//nolint:mnd // u+rwx,go=-
	if e := os.MkdirAll(filepath.Dir(fn), 0o700); e != nil {
		return errors.Newf("failed to created directory: %w", e)
	}

	// Open file
	if !appendToFile {
		f, e = os.Create(filepath.Clean(fn))
	} else {
		//nolint:mnd // u+rw,go=-
		f, e = os.OpenFile(
			filepath.Clean(fn),
			os.O_APPEND|os.O_CREATE|os.O_WRONLY,
			0o600,
		)
	}

	if e != nil {
		return errors.Newf("failed to open file: %w", e)
	}
	defer func() {
		if e == nil {
			e = f.Close()
		}
	}()

	if _, e = f.WriteString(sb.String()); e != nil {
		return errors.Newf("failed to write to file: %w", e)
	}

	return nil
}
